import { Poll } from '@/types/poll';
import { parseSTX } from './stacks';


// Mock data for development - replace with actual contract calls
export const mockPolls: Poll[] = [
  {
    id: '1',
    creator: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM',
    question: 'What should be the next major feature for Stacks?',
    options: [
      { id: 0, text: 'sBTC Integration', votes: 45 },
      { id: 1, text: 'Layer 2 Scaling', votes: 32 },
      { id: 2, text: 'NFT Improvements', votes: 28 },
      { id: 3, text: 'DeFi Tooling', votes: 19 },
    ],
    voteFee: parseSTX(0.5),
    rewardPool: parseSTX(50),
    endBlock: 150000,
    currentBlock: 145000,
    totalVotes: 124,
    isActive: true,
  },
  {
    id: '2',
    creator: 'ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG',
    question: 'Best time for community calls?',
    options: [
      { id: 0, text: '9 AM UTC', votes: 67 },
      { id: 1, text: '3 PM UTC', votes: 89 },
      { id: 2, text: '9 PM UTC', votes: 54 },
    ],
    voteFee: parseSTX(0.1),
    rewardPool: parseSTX(10),
    endBlock: 148000,
    currentBlock: 145000,
    totalVotes: 210,
    isActive: true,
  },
  {
    id: '3',
    creator: 'ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0',
    question: 'Which blockchain has the best developer experience?',
    options: [
      { id: 0, text: 'Stacks', votes: 156 },
      { id: 1, text: 'Ethereum', votes: 98 },
      { id: 2, text: 'Solana', votes: 45 },
      { id: 3, text: 'Other', votes: 23 },
    ],
    voteFee: parseSTX(0.25),
    rewardPool: parseSTX(100),
    endBlock: 140000,
    currentBlock: 145000,
    totalVotes: 322,
    isActive: false,
    canClaim: true,
  },
  {
    id: '4',
    creator: 'ST4NX9F1A7K5B2QXH4L8WMCN6Y7D8V1TSR6Z0ABCD',
    question: 'Which Stacks wallet do you prefer?',
    options: [
      { id: 0, text: 'Hiro Wallet', votes: 120 },
      { id: 1, text: 'Xverse', votes: 75 },
      { id: 2, text: 'Other', votes: 30 },
    ],
    voteFee: parseSTX(0.05),
    rewardPool: parseSTX(20),
    endBlock: 152000,
    currentBlock: 145000,
    totalVotes: 225,
    isActive: true,
  },
  {
    id: '5',
    creator: 'ST5LKD8A1J2M4QXW5C9V7NMH8Y3Z6E2T1R5P0ABCD',
    question: 'Preferred type of NFT project on Stacks?',
    options: [
      { id: 0, text: 'Art Collectibles', votes: 88 },
      { id: 1, text: 'Music NFTs', votes: 42 },
      { id: 2, text: 'Gaming NFTs', votes: 105 },
      { id: 3, text: 'Other', votes: 15 },
    ],
    voteFee: parseSTX(0.2),
    rewardPool: parseSTX(60),
    endBlock: 155000,
    currentBlock: 145000,
    totalVotes: 250,
    isActive: true,
  },
  {
    id: '6',
    creator: 'ST6QRX2A5K3F1B9D4V6N8H2Y5Z7C1M3T4R9ABCD',
    question: 'Should Stacks focus on enterprise adoption or community growth?',
    options: [
      { id: 0, text: 'Enterprise Adoption', votes: 95 },
      { id: 1, text: 'Community Growth', votes: 130 },
    ],
    voteFee: parseSTX(0.3),
    rewardPool: parseSTX(80),
    endBlock: 158000,
    currentBlock: 145000,
    totalVotes: 225,
    isActive: true,
  },

  // --- Additional Polls ---
  {
    id: '7',
    creator: 'ST7ABCD1234567890XYZ',
    question: 'Favorite Stacks SDK for app development?',
    options: [
      { id: 0, text: 'Clarinet', votes: 80 },
      { id: 1, text: 'Stacks.js', votes: 110 },
      { id: 2, text: 'Other', votes: 15 },
    ],
    voteFee: parseSTX(0.05),
    rewardPool: parseSTX(30),
    endBlock: 160000,
    currentBlock: 145000,
    totalVotes: 205,
    isActive: true,
  },
  {
    id: '8',
    creator: 'ST8ABCD9876543210XYZ',
    question: 'Should Stacks focus on Bitcoin integration or DeFi expansion?',
    options: [
      { id: 0, text: 'Bitcoin Integration', votes: 90 },
      { id: 1, text: 'DeFi Expansion', votes: 60 },
    ],
    voteFee: parseSTX(0.2),
    rewardPool: parseSTX(40),
    endBlock: 162000,
    currentBlock: 145000,
    totalVotes: 150,
    isActive: true,
  },
  {
    id: '9',
    creator: 'ST9ABCD1122334455XYZ',
    question: 'Which feature is more important for NFTs?',
    options: [
      { id: 0, text: 'Royalties', votes: 120 },
      { id: 1, text: 'Interoperability', votes: 85 },
      { id: 2, text: 'Rarity', votes: 70 },
    ],
    voteFee: parseSTX(0.1),
    rewardPool: parseSTX(50),
    endBlock: 164000,
    currentBlock: 145000,
    totalVotes: 275,
    isActive: true,
  },
  {
    id: '10',
    creator: 'ST10ABCD5566778899XYZ',
    question: 'Best way to onboard new Stacks users?',
    options: [
      { id: 0, text: 'Educational Content', votes: 140 },
      { id: 1, text: 'Grants & Incentives', votes: 110 },
      { id: 2, text: 'Community Events', votes: 60 },
    ],
    voteFee: parseSTX(0.15),
    rewardPool: parseSTX(70),
    endBlock: 166000,
    currentBlock: 145000,
    totalVotes: 310,
    isActive: true,
  },
  {
    id: '11',
    creator: 'ST11ABCD9988776655XYZ',
    question: 'Which community tool do you use the most?',
    options: [
      { id: 0, text: 'Discord', votes: 150 },
      { id: 1, text: 'Telegram', votes: 75 },
      { id: 2, text: 'Twitter Spaces', votes: 65 },
    ],
    voteFee: parseSTX(0.05),
    rewardPool: parseSTX(25),
    endBlock: 168000,
    currentBlock: 145000,
    totalVotes: 290,
    isActive: true,
  },
  {
    id: '12',
    creator: 'ST12ABCD2233445566XYZ',
    question: 'Preferred Stacks smart contract language?',
    options: [
      { id: 0, text: 'Clarity', votes: 220 },
      { id: 1, text: 'Other', votes: 35 },
    ],
    voteFee: parseSTX(0.25),
    rewardPool: parseSTX(90),
    endBlock: 170000,
    currentBlock: 145000,
    totalVotes: 255,
    isActive: false,
    canClaim: true,
  },
  {
    id: '13',
    creator: 'ST13ABCD6677889900XYZ',
    question: 'What is the main reason you hold STX?',
    options: [
      { id: 0, text: 'Staking', votes: 180 },
      { id: 1, text: 'Governance', votes: 90 },
      { id: 2, text: 'NFTs', votes: 40 },
    ],
    voteFee: parseSTX(0.05),
    rewardPool: parseSTX(20),
    endBlock: 172000,
    currentBlock: 145000,
    totalVotes: 310,
    isActive: true,
  },
  {
    id: '14',
    creator: 'ST14ABCD4455667788XYZ',
    question: 'Should Stacks expand to DeFi or Gaming first?',
    options: [
      { id: 0, text: 'DeFi', votes: 100 },
      { id: 1, text: 'Gaming', votes: 125 },
    ],
    voteFee: parseSTX(0.1),
    rewardPool: parseSTX(50),
    endBlock: 174000,
    currentBlock: 145000,
    totalVotes: 225,
    isActive: true,
  },
  {
    id: '15',
    creator: 'ST15ABCD5566778899XYZ',
    question: 'Favorite type of NFT utility?',
    options: [
      { id: 0, text: 'Access Passes', votes: 95 },
      { id: 1, text: 'Royalties', votes: 65 },
      { id: 2, text: 'Gaming Items', votes: 105 },
    ],
    voteFee: parseSTX(0.2),
    rewardPool: parseSTX(60),
    endBlock: 176000,
    currentBlock: 145000,
    totalVotes: 265,
    isActive: true,
  },
  {
    id: '16',
    creator: 'ST16ABCD6677889900XYZ',
    question: 'Preferred type of community engagement?',
    options: [
      { id: 0, text: 'AMA Sessions', votes: 120 },
      { id: 1, text: 'Polls', votes: 140 },
      { id: 2, text: 'Contests', votes: 85 },
    ],
    voteFee: parseSTX(0.05),
    rewardPool: parseSTX(30),
    endBlock: 178000,
    currentBlock: 145000,
    totalVotes: 345,
    isActive: true,
  },
  {
    id: '17',
    creator: 'ST17ABCD7788990011XYZ',
    question: 'Which layer 2 solution is most promising?',
    options: [
      { id: 0, text: 'Stacks L2', votes: 80 },
      { id: 1, text: 'Polygon', votes: 60 },
      { id: 2, text: 'Optimism', votes: 50 },
      { id: 3, text: 'Other', votes: 20 },
    ],
    voteFee: parseSTX(0.15),
    rewardPool: parseSTX(40),
    endBlock: 180000,
    currentBlock: 145000,
    totalVotes: 210,
    isActive: true,
  },
];
